ALTER TABLE employes_rh 
ADD COLUMN IF NOT EXISTS poste TEXT DEFAULT 'Auxiliaire',
ADD COLUMN IF NOT EXISTS poste_autre TEXT,
ADD COLUMN IF NOT EXISTS adresse TEXT,
ADD COLUMN IF NOT EXISTS telephone TEXT;
