-- Compte de passif pour les abonnements prepayes (recette d'avance)
insert into public.comptes (numero, libelle, type, actif)
values ('2031', 'Abonnements journees prepayees', 'passif', true)
on conflict (numero) do update set libelle = excluded.libelle, type = excluded.type, actif = true;

-- Regrouper tout le service sous 3000 : desactiver 3001 (inutilise par le moteur)
update public.comptes set actif = false where numero = '3001';

-- Table des cartes achetees
create table if not exists public.abonnements (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.clients(id),
  numero integer generated by default as identity,
  tarif_unitaire numeric not null,
  jours_total integer not null default 11,
  jours_offerts integer not null default 1,
  prix_paye numeric not null,
  mode_paiement text,
  statut text not null default 'en_attente_paiement',
  date_commande date not null default current_date,
  date_paiement date,
  date_expiration date,
  created_by uuid,
  created_at timestamptz not null default now(),
  constraint abonnements_statut_check check (statut = any (array['en_attente_paiement','actif','epuise','expire','annule'])),
  constraint abonnements_mode_paiement_check check (mode_paiement is null or mode_paiement = any (array['cash','twint','virement','stripe','avoir']))
);

-- Journal append-only des journees (solde = somme des delta)
create table if not exists public.abonnements_mouvements (
  id uuid primary key default gen_random_uuid(),
  abonnement_id uuid not null references public.abonnements(id),
  client_id uuid not null references public.clients(id),
  delta integer not null,
  type text not null,
  reservation_id uuid references public.reservations(id),
  motif text,
  created_by uuid,
  created_at timestamptz not null default now(),
  constraint abonnements_mouvements_type_check check (type = any (array['achat','consommation','recredit','expiration','ajustement']))
);

-- Lien reservation journee -> carte
alter table public.reservations add column if not exists abonnement_id uuid references public.abonnements(id);

-- Index
create index if not exists idx_abonnements_client on public.abonnements(client_id);
create index if not exists idx_abonnements_statut on public.abonnements(statut);
create index if not exists idx_abo_mouv_abonnement on public.abonnements_mouvements(abonnement_id);
create index if not exists idx_abo_mouv_client on public.abonnements_mouvements(client_id);
create index if not exists idx_abo_mouv_reservation on public.abonnements_mouvements(reservation_id);
create index if not exists idx_reservations_abonnement on public.reservations(abonnement_id);

-- Append-only sur le journal des mouvements
create or replace function public.abonnements_mouvements_append_only()
 returns trigger
 language plpgsql
 set search_path to ''
as $function$
begin
  raise exception 'abonnements_mouvements est append-only : un mouvement ne peut etre ni modifie ni supprime';
end;
$function$;

revoke execute on function public.abonnements_mouvements_append_only() from public, anon, authenticated;

drop trigger if exists trg_abonnements_mouvements_append_only on public.abonnements_mouvements;
create trigger trg_abonnements_mouvements_append_only
  before delete or update on public.abonnements_mouvements
  for each row execute function public.abonnements_mouvements_append_only();

-- RLS (forme optimisee (select ...) pour la perf)
alter table public.abonnements enable row level security;
alter table public.abonnements_mouvements enable row level security;

create policy admin_all_abonnements on public.abonnements
  as permissive for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
create policy client_select_abonnements on public.abonnements
  as permissive for select to authenticated
  using (client_id in (select id from public.clients where auth_user_id = (select auth.uid())));
create policy personnel_select_abonnements on public.abonnements
  as permissive for select to authenticated
  using ((select public.is_personnel()));

create policy admin_all_abonnements_mouvements on public.abonnements_mouvements
  as permissive for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
create policy client_select_abonnements_mouvements on public.abonnements_mouvements
  as permissive for select to authenticated
  using (client_id in (select id from public.clients where auth_user_id = (select auth.uid())));
create policy personnel_select_abonnements_mouvements on public.abonnements_mouvements
  as permissive for select to authenticated
  using ((select public.is_personnel()));
